[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# ✅ إعادة كتابة (rewrites) عشان تختصر المسارات
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200